# Generated by Django 3.2 on 2021-04-13 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadb',
            old_name='ids',
            new_name='name',
        ),
    ]
